server {
    listen 8088;
    server_name _;
    root /var/www/mind41-landing/current;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ /\. {
        deny all;
    }
}
